name: carpark
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder num ber may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.1+2

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  easy_sidemenu: ^0.6.0
  shared_preferences: ^2.3.5
  jwt_decode: ^0.3.1
  dropdown_button2: ^2.3.9
  flutter_form_builder: ^9.7.0
  form_builder_validators: ^11.1.1
  rflutter_alert: ^2.0.7
  path_provider: ^2.1.5
  csv: ^6.0.0
  flutter_esc_pos_utils: ^1.0.1
  image: ^4.3.0
  charset_converter: ^2.3.0
  hooks_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  searchfield: ^1.2.2
  substring_highlight: ^1.0.33
  retrofit: ^4.4.2
  dio: ^5.7.0
  logger: ^2.5.0
  json_annotation: ^4.9.0
  get_it: ^8.0.3
  calendar_date_picker2: ^1.1.8
  riverpod_annotation: ^2.6.1
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  qr_flutter: ^4.1.0
  flutter_easyloading: ^3.0.5
  file_saver: ^0.2.14
  excel: ^4.0.6
  file_picker: ^8.1.7
  media_kit: ^1.1.7
  media_kit_video: ^1.1.8
  media_kit_libs_video: ^1.0.1
  web_socket_channel: ^3.0.1
  thermal_printer: ^1.0.5
  text_marquee: ^0.0.2
  flutter_bloc: ^8.1.6
  injectable: ^2.5.0
  fpdart: ^1.1.1
  uuid: ^4.5.1
  duration: ^4.0.3
  web: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^9.1.7
  build_runner: ^2.4.14
  json_serializable: ^6.9.0
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.3
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Stidti
      fonts:
        - asset: fonts/Stidti-Regular.otf
        - asset: fonts/Stidti-Bold.otf
    - family: NotoSerif
      fonts:
        - asset: fonts/NotoSerifThai-Regular.ttf
        - asset: fonts/NotoSerifThai-Bold.ttf
